name: iea-pre-commit
description: run pre-commit to auto-fix as much as we can
author: 'Connor Bell'
branding:
  icon: 'activity'
  color: 'blue'
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'

runs:
  using: 'node16'
  main: 'dist/index.js'
